GLOBAL.TUNING.wasphive = GetModConfigData("wasphive")
GLOBAL.TUNING.houndmound = GetModConfigData("houndmound")
GLOBAL.TUNING.pighouse = GetModConfigData("pighouse")
GLOBAL.TUNING.mermhouse = GetModConfigData("mermhouse")
GLOBAL.TUNING.spiderden = GetModConfigData("spiderden")
GLOBAL.TUNING.tallbirdnest = GetModConfigData("tallbirdnest")
GLOBAL.TUNING.tentacle = GetModConfigData("tentacle")
GLOBAL.TUNING.beefalo = GetModConfigData("beefalo")
GLOBAL.TUNING.lightninggoat = GetModConfigData("lightninggoat")
GLOBAL.TUNING.knight = GetModConfigData("knight")
GLOBAL.TUNING.bishop = GetModConfigData("bishop")
GLOBAL.TUNING.rook = GetModConfigData("rook")

AddPrefabPostInit("forest", function(inst)
	inst:AddComponent("monsterspawner")
end)