GLOBAL.TUNING.MG = {}
GLOBAL.TUNING.MG.wasphive = GetModConfigData("wasphive")
GLOBAL.TUNING.MG.houndmound = GetModConfigData("houndmound")
GLOBAL.TUNING.MG.pighouse = GetModConfigData("pighouse")
GLOBAL.TUNING.MG.mermhouse = GetModConfigData("mermhouse")
GLOBAL.TUNING.MG.spiderden = GetModConfigData("spiderden")
GLOBAL.TUNING.MG.tallbirdnest = GetModConfigData("tallbirdnest")
GLOBAL.TUNING.MG.tentacle = GetModConfigData("tentacle")
GLOBAL.TUNING.MG.beefalo = GetModConfigData("beefalo")
GLOBAL.TUNING.MG.lightninggoat = GetModConfigData("lightninggoat")
GLOBAL.TUNING.MG.knight = GetModConfigData("knight")
GLOBAL.TUNING.MG.bishop = GetModConfigData("bishop")
GLOBAL.TUNING.MG.rook = GetModConfigData("rook")
GLOBAL.TUNING.MG.catcoonden = GetModConfigData("catcoonden")

AddPrefabPostInit("forest", function(inst)
	inst:AddComponent("monsterspawner")
end)